name: demo python code
on: push
jobs:
  check the output of code
  runs_on:ubuntu-latest
  steps:
  
  - uses: actions/checkout@master
        
        
  - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
  - name: install python packages
    run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       
  -run: sum.py
